# This is a basic workflow to help you get started with Actions

name: BuildSite

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Add Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Add GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          platform: x64
          
      - name: Add Make
        run: sudo apt-get -y install make
        
      - name: Add Ruby + Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
      - name: Install NPM Dependancies
        run: npm ci
        
      - name: Build Site
        run: npm run build
      
      - name: Remove Old Site
        run: rm -rf $GITHUB_WORKSPACE/docs/*
      
      - name: Copy New Site
        run: cp -r $GITHUB_WORKSPACE/_site/* $GITHUB_WORKSPACE/docs/
        
      - name: Commit changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: $GITHUB_WORKSPACE/docs
